apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.frontend-nodeport-access
spec:
  tier: security
  order: 100
  selector: node-role.kubernetes.io/worker == "true"
  namespaceSelector: ''
  serviceAccountSelector: ''
  ingress:
    - action: Allow
      source: {}
      destination:
        nets:
          - 127.0.0.1/32
    - action: Deny
      protocol: TCP
      source: {}
      destination:
        ports:
          - '30080'
  doNotTrack: false
  applyOnForward: true
  preDNAT: true
  types:
    - Ingress
